# === Analysis configuration file ======================================================

# --- Configuration for custom analyses in Snakefile outside of seqneut-pipeline --------

# For the most part our analyses separate recent and historical vaccine strains, but
# consider these vaccine strains to be "recent" and include them alongside the recent strains.
recent_vaccine_strains:
  A/Croatia/10136RV/2023-egg_H3N2: 2025-2026 egg-based vaccine
  A/DistrictOfColumbia/27/2023_H3N2: 2025-2026 cell-based vaccine
  A/Victoria/4897/2022_IVR-238_H1N1: 2025-2026 egg-based vaccine
  A/Wisconsin/67/2022_H1N1: 2025-2026 cell-based vaccine
  A/Thailand/8/2022_H3N2: 2024-2025 egg-based vaccine
  A/Massachusetts/18/2022_H3N2: 2024-2025 cell-based vaccine

# Configuration relevant to aggregated analyses of human sera titeres
human_sera_groups_to_exclude:  # sera groups excluded from aggregated human sera analysis
  - FCI  # these are ferret sera
human_sera_to_exclude: []  # individual sera excluded from aggregated human sera analysis

# Configuration for plots of titers against human sera
human_sera_plots_params:
  titer_cutoff: 140  # similar to that in https://elifesciences.org/reviewed-preprints/106811
  titer_lower_limit: 40  # lower limit of titers in assay
  min_frac_strains: 0.8  # only include sera w titers against this fraction of strains
  min_frac_sera: 0.8  # only include strains w titers against this fraction of ssera
  min_frac_action: drop  # "drop" sera/strains below min_frac, or "raise" error


# --- Configuration for `seqneut-pipeline` ----------------------------------------------

seqneut-pipeline: seqneut-pipeline

docs: docs

description: |
  # Sequencing-based neutralization assays using human serum samples collected in late 2024-2025 and combined pdmH1N1 and H3N2 influenza library

  The numerical data and computer code are at [https://github.com/jbloomlab/flu-seqneut-2025](https://github.com/jbloomlab/flu-seqneut-2025)


viral_libraries:
  flu-seqneut-2025_library_designed: data/viral_libraries/flu-seqneut-2025-barcode-to-strain_designed.csv
  flu-seqneut-2025_library_actual: data/viral_libraries/flu-seqneut-2025-barcode-to-strain_actual.csv

viral_strain_plot_order: data/viral_libraries/flu-seqneut-2025_plot_order.csv

neut_standard_sets:
  loes2023: data/neut_standard_sets/loes2023_neut_standards.csv

illumina_barcode_parser_params:
  upstream: CCTACAATGTCGGATTTGTATTTAATAG
  downstream: ''
  minq: 20
  upstream_mismatch: 4
  bc_orientation: R2

default_process_plate_qc_thresholds: &default_process_plate_qc_thresholds
  avg_barcode_counts_per_well: 500
  min_neut_standard_frac_per_well: 0.005
  no_serum_per_viral_barcode_filters:
    min_frac: 0.0001
    max_fold_change: 4
    max_wells: 2
  per_neut_standard_barcode_filters:
    min_frac: 0.005
    max_fold_change: 4
    max_wells: 2
  min_neut_standard_count_per_well: 1000
  min_no_serum_count_per_viral_barcode_well: 100
  max_frac_infectivity_per_viral_barcode_well: 3
  min_dilutions_per_barcode_serum_replicate: 6

default_process_plate_curvefit_params: &default_process_plate_curvefit_params
  frac_infectivity_ceiling: 1
  fixtop: [0.6, 1] 
  fixbottom: 0
  fixslope: [0.8, 10]

default_process_plate_curvefit_qc:  &default_process_plate_curvefit_qc
  max_frac_infectivity_at_least: 0.0  # Allow 'completely neutralized' straight lines to be fit
  goodness_of_fit:  # EITHER R2 must be >= min_R2 or RMSD must be <= max_RMSD
    min_R2: 0.5
    max_RMSD: 0.15  # you may be able to increase this to more like 0.1
  serum_replicates_ignore_curvefit_qc: []
  barcode_serum_replicates_ignore_curvefit_qc: []

default_serum_titer_as: midpoint

default_serum_qc_thresholds: &default_serum_qc_thresholds
  min_replicates: 1
  max_fold_change_from_median: 6
  viruses_ignore_qc: []

sera_override_defaults: {}

plates:

# plate1 and plate2 are dropped from the analysis due to unbalanced sequencing
  # plate1:
  #   group: UWMC
  #   date: 2025-07-23
  #   viral_library: flu-seqneut-2025_library_actual
  #   neut_standard_set: loes2023
  #   samples_csv: data/plates/2024-07-23_plate1.csv
  #   manual_drops: {}
  #   qc_thresholds:
  #     <<: *default_process_plate_qc_thresholds
  #   curvefit_params:
  #     <<: *default_process_plate_curvefit_params
  #   curvefit_qc:
  #     <<: *default_process_plate_curvefit_qc
  #   illumina_barcode_parser_params:
  #     upstream2: ATCGAT # Fwd2
  #     upstream2_mismatch: 1

  # plate2:
  #   group: UWMC
  #   date: 2025-07-23
  #   viral_library: flu-seqneut-2025_library_actual
  #   neut_standard_set: loes2023
  #   samples_csv: data/plates/2024-07-23_plate2.csv
  #   manual_drops: {}
  #   qc_thresholds:
  #     <<: *default_process_plate_qc_thresholds
  #   curvefit_params:
  #     <<: *default_process_plate_curvefit_params
  #   curvefit_qc:
  #     <<: *default_process_plate_curvefit_qc
  #   illumina_barcode_parser_params:
  #     upstream2: TGACGC # Fwd3
  #     upstream2_mismatch: 1

  plate1-2:
    group: UWMC
    date: 2025-08-07
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-11_plate1-2.csv
    manual_drops:
      wells:
        - H1
        - H2
        - H3
        - H4
        - H5
        - H6
        - H7
        - H8
        - H9
        - H10
        - H11
        - H12
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ATCGAT # Fwd2
      upstream2_mismatch: 1

  plate2-2:
    group: UWMC
    date: 2025-08-07
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-11_plate2-2.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1

  plate3:
    group: UWMC
    date: 2025-08-07
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-11_plate3.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CAGTTG # Fwd4
      upstream2_mismatch: 1

  plate4:
    group: UWMC
    date: 2025-08-07
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-11_plate4.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GTCTAA # Fwd5
      upstream2_mismatch: 1

# plate5 is dropped from the analysis due to experimental error
  # plate5:
  #   group: UWMC
  #   date: 2025-08-12
  #   viral_library: flu-seqneut-2025_library_actual
  #   neut_standard_set: loes2023
  #   samples_csv: data/plates/2025-08-12_plate5.csv
  #   manual_drops: {}
  #   qc_thresholds:
  #     <<: *default_process_plate_qc_thresholds
  #   curvefit_params:
  #     <<: *default_process_plate_curvefit_params
  #   curvefit_qc:
  #     <<: *default_process_plate_curvefit_qc
  #   illumina_barcode_parser_params:
  #     upstream2: GCTACA # Fwd1
  #     upstream2_mismatch: 1
  
  plate6:
    group: FCI
    date: 2025-08-12
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-12_plate6.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ATCGAT # Fwd2
      upstream2_mismatch: 1

  plate7_FCI:
    group: FCI
    date: 2025-08-12
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-12_plate7_FCI.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1

  plate7_SCH:
    group: SCH
    date: 2025-08-12
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-12_plate7_SCH.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1
  
  plate8:
    group: SCH
    date: 2025-08-12
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-12_plate8.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CAGTTG # Fwd4
      upstream2_mismatch: 1

  plate9:
    group: SCH
    date: 2025-08-13
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-13_plate9.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GTCTAA # Fwd5
      upstream2_mismatch: 1

  plate10:
    group: SCH
    date: 2025-08-13
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-13_plate10.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ACGCTG # Fwd6
      upstream2_mismatch: 1

  plate11:
    group: SCH
    date: 2025-08-13
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-13_plate11.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TATAGC # Fwd7
      upstream2_mismatch: 1

  plate12_SCH:
    group: SCH
    date: 2025-08-13
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-13_plate12_SCH.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CGAGCT # Fwd8
      upstream2_mismatch: 1

  plate12_EPIHK:
    group: EPIHK
    date: 2025-08-13
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-13_plate12_EPIHK.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CGAGCT # Fwd8
      upstream2_mismatch: 1

  plate13:
    group: EPIHK
    date: 2025-08-18
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-18_plate13.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GCTACA # Fwd1
      upstream2_mismatch: 1

  plate14:
    group: EPIHK
    date: 2025-08-18
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-18_plate14.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ATCGAT # Fwd2
      upstream2_mismatch: 1

  plate15:
    group: EPIHK
    date: 2025-08-18
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-18_plate15.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TGACGC # Fwd3
      upstream2_mismatch: 1

  plate16:
    group: NIID
    date: 2025-08-18
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-18_plate16.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CAGTTG # Fwd4
      upstream2_mismatch: 1
  
  plate17:
    group: NIID
    date: 2025-08-20
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-20_plate17.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: GTCTAA # Fwd5
      upstream2_mismatch: 1

  plate18:
    group: NIID
    date: 2025-08-20
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-20_plate18.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: ACGCTG # Fwd6
      upstream2_mismatch: 1

  plate19:
    group: NIID
    date: 2025-08-20
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-20_plate19.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: TATAGC # Fwd7
      upstream2_mismatch: 1

  plate20:
    group: NIID
    date: 2025-08-20
    viral_library: flu-seqneut-2025_library_actual
    neut_standard_set: loes2023
    samples_csv: data/plates/2025-08-20_plate20.csv
    manual_drops: {}
    qc_thresholds:
      <<: *default_process_plate_qc_thresholds
    curvefit_params:
      <<: *default_process_plate_curvefit_params
    curvefit_qc:
      <<: *default_process_plate_curvefit_qc
    illumina_barcode_parser_params:
      upstream2: CGAGCT # Fwd8
      upstream2_mismatch: 1
      

miscellaneous_plates:

    20250716_initial_pool:
      date: 2025-07-16
      viral_library: flu-seqneut-2025_library_designed
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-07-16_initial_pool.csv
      illumina_barcode_parser_params:
        upstream2: GCTACA # Fwd1
        upstream2_mismatch: 1

    20250723_balanced_pool:
      date: 2025-07-23
      viral_library: flu-seqneut-2025_library_designed
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-07-23_balanced_repool.csv
      illumina_barcode_parser_params:
        upstream2: GCTACA # Fwd1
        upstream2_mismatch: 1

    20250723_H3_and_partial_H1_balanced_pool:
      date: 2025-07-23
      viral_library: flu-seqneut-2025_library_designed
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-07-23_H3_and_partial_H1_balanced_repool.csv
      illumina_barcode_parser_params:
        upstream2: GCTACA # Fwd1
        upstream2_mismatch: 1

    20250807_balanced_pool:
      date: 2025-08-07
      viral_library: flu-seqneut-2025_library_designed
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-08-07_balanced_repool.csv
      illumina_barcode_parser_params:
        upstream2: GCTACA # Fwd1
        upstream2_mismatch: 1
