# === Analysis configuration file ======================================================

# --- Configuration for `seqneut-pipeline` ---------------------------------------------

seqneut-pipeline: seqneut-pipeline

docs: docs

description: |
  # Sequencing-based neutralization assays using human serum samples collected in late 2024-2025 and combined pdmH1N1 and H3N2 influenza library

  The numerical data and computer code are at [https://github.com/jbloomlab/flu-seqneut-2025](https://github.com/jbloomlab/flu-seqneut-2025)


viral_libraries:
  flu-seqneut-2025_library: data/viral_libraries/flu-seqneut-2025-barcode-to-strain.csv

# viral_strain_plot_order: data/H3N2library_2023-2024_strain_order.csv

neut_standard_sets:
  loes2023: data/neut_standard_sets/loes2023_neut_standards.csv

illumina_barcode_parser_params:
  upstream: CCTACAATGTCGGATTTGTATTTAATAG
  downstream: ''
  minq: 20
  upstream_mismatch: 4
  bc_orientation: R2

default_process_plate_qc_thresholds: &default_process_plate_qc_thresholds
  avg_barcode_counts_per_well: 500
  min_neut_standard_frac_per_well: 0.005
  no_serum_per_viral_barcode_filters:
    min_frac: 0.0001
    max_fold_change: 4
    max_wells: 2
  per_neut_standard_barcode_filters:
    min_frac: 0.005
    max_fold_change: 4
    max_wells: 2
  min_neut_standard_count_per_well: 1000
  min_no_serum_count_per_viral_barcode_well: 100
  max_frac_infectivity_per_viral_barcode_well: 3
  min_dilutions_per_barcode_serum_replicate: 6

default_process_plate_curvefit_params: &default_process_plate_curvefit_params
  frac_infectivity_ceiling: 1
  fixtop: [0.6, 1] 
  fixbottom: 0
  fixslope: [0.8, 10]

default_process_plate_curvefit_qc:  &default_process_plate_curvefit_qc
  max_frac_infectivity_at_least: 0.0  # Allow 'completely neutralized' straight lines to be fit
  goodness_of_fit:  # EITHER R2 must be >= min_R2 or RMSD must be <= max_RMSD
    min_R2: 0.5
    max_RMSD: 0.15  # you may be able to increase this to more like 0.1
  serum_replicates_ignore_curvefit_qc: []
  barcode_serum_replicates_ignore_curvefit_qc: []

default_serum_titer_as: midpoint

default_serum_qc_thresholds: &default_serum_qc_thresholds
  min_replicates: 2
  max_fold_change_from_median: 6
  viruses_ignore_qc: []

sera_override_defaults: {}

plates: {}

miscellaneous_plates:

    20250716_initial_pool:
      date: 2025-07-16
      viral_library: flu-seqneut-2025_library
      neut_standard_set: loes2023
      samples_csv: data/miscellaneous_plates/2025-07-16_initial_pool.csv
      illumina_barcode_parser_params:
        upstream2: GCTACA # Fwd1
        upstream2_mismatch: 1
