"""Top-level ``snakemake`` file that runs analysis."""

import pandas as pd
from os.path import join

configfile: "config.yml"

include: "seqneut-pipeline/seqneut-pipeline.smk"


# auspice JSONs as target output
auspice_jsons = []
if "nextstrain-prot-titers-tree_config" in config:
    for d in config["nextstrain-prot-titers-tree_config"].values():
        auspice_jsons.append(d["auspice_json"])
        if "titers" in d:
            auspice_jsons.append(os.path.splitext(d["auspice_json"])[0] + "_measurements.json")

rule all:
    input:
        # output from seqneut-pipeline
        seqneut_pipeline_outputs,
        # outputs from custom analyses
        "results/viral_strain_seqs/recent_HA_ectodomain_nts.fa",
        "results/viral_strain_seqs/recent_HA_ectodomain_prots.fa",
        "results/aggregated_analyses/human_sera_metadata.csv",
        "results/aggregated_analyses/human_sera_titers.csv",
        "results/aggregated_analyses/human_sera_titers_summarized.csv",
        [auspice_jsons],


# --- Everything below here is a custom analysis not part of seqneut-pipeline -----------

rule recent_strains_fasta:
    """Generate FASTA of recent strains in library."""
    input:
        csv=config["viral_libraries"]["actual"],
    output:
        nt_fasta="results/viral_strain_seqs/recent_HA_ectodomain_nts.fa",
        prot_fasta="results/viral_strain_seqs/recent_HA_ectodomain_prots.fa",
    params:
        circulating_strain_type=config["circulating_strain_type"],
        recent_vaccine_strains=config["recent_vaccine_strains"],  # also include these
    conda:
        "seqneut-pipeline/environment.yml"
    log:
        "results/logs/recent_strains_fasta.txt",
    script:
        "scripts/recent_strains_fasta.py"


# human sera groups to use in aggregated analyses of human sera titers
human_sera_groups_to_analyze = [
    g for g in groups if g not in config["human_sera_groups_to_exclude"]
]

rule aggregate_human_sera_metadata_and_titers:
    """Aggregate metadata and titers on human sera."""
    input:
        groups_metadata=expand(
            "data/sera_metadata/{group}_metadata.csv", group=human_sera_groups_to_analyze
        ),
        group_titers=expand(
            "results/aggregated_titers/titers_{group}.csv",
            group=human_sera_groups_to_analyze,
        ),
    params:
        groups=human_sera_groups_to_analyze,
        human_sera_to_exclude=config["human_sera_to_exclude"],
    output:
        metadata_csv="results/aggregated_analyses/human_sera_metadata.csv",
        titers_csv="results/aggregated_analyses/human_sera_titers.csv",
    conda:
        "seqneut-pipeline/environment.yml"
    log:
        notebook="results/aggregated_analyses/aggregate_human_sera_metadata_and_titers.ipynb",
    notebook:
        "notebooks/aggregate_human_sera_metadata_and_titers.py.ipynb"


rule plot_human_sera_titers:
    input:
        metadata_csv="results/aggregated_analyses/human_sera_metadata.csv",
        titers_csv="results/aggregated_analyses/human_sera_titers.csv",
        virus_csv=config["viral_libraries"]["actual"],
        viral_strain_plot_order=config["viral_strain_plot_order"],
    output:
        sera_collection_date_and_age_plot='results/aggregated_analyses/sera_collection_dates_and_ages.html',
        chart_htmls=[
            f"results/aggregated_analyses/human_sera_titers_{subtype}_{strain_type}_{chart_type}.html"
            for subtype in config["subtypes"]
            for strain_type in ["recent", "vaccine"]
            for chart_type in ["individual_sera", "interquartile_range", "frac_below_cutoff"]
        ],
        summarized_titers_csv="results/aggregated_analyses/human_sera_titers_summarized.csv",
    params:
        recent_vaccine_strains=config["recent_vaccine_strains"],
        human_sera_plots_params=config["human_sera_plots_params"],
        circulating_strain_type=config["circulating_strain_type"],
    conda:
        "seqneut-pipeline/environment.yml"
    log:
        notebook="results/aggregated_analyses/plot_human_sera_titers.ipynb",
    notebook:
        "notebooks/plot_human_sera_titers.py.ipynb"


# add custom summary plots to docs HTMLs generated by pipeline
add_htmls_to_docs = {
    "Interactive charts summarizing human sera titers": {
        "Notebook making interactive charts": "results/aggregated_analyses/plot_human_sera_titers.html"
    } | {
        f"Chart for {subtype} {strain_type} strains {chart_type}":
            f"results/aggregated_analyses/human_sera_titers_{subtype}_{strain_type}_{chart_type}.html"
        for subtype in config["subtypes"]
        for strain_type in ["recent", "vaccine"]
        for chart_type in ["individual_sera", "interquartile_range", "frac_below_cutoff"]
    }
}


rule nextstrain_prot_titers_tree_alignment_and_metadata:
    """Build alignment and metadata used by `nextstrain-prot-titers-tree`."""
    input:
        viral_libraries_csv=config["viral_libraries"]["actual"],
        summarized_titers_csv="results/aggregated_analyses/human_sera_titers_summarized.csv",
        titers_csv="results/aggregated_analyses/human_sera_titers.csv",
        sera_metadata_csv="results/aggregated_analyses/human_sera_metadata.csv",
    output:
        **{
            f"alignment_{subtype}": f"results/nextstrain-prot-titers-tree/{subtype}/alignment.fa"
            for subtype in config["subtypes"]
        },
        **{
            f"metadata_{subtype}": f"results/nextstrain-prot-titers-tree/{subtype}/metadata.tsv"
            for subtype in config["subtypes"]
        },
        **{
            f"titers_{subtype}": f"results/nextstrain-prot-titers-tree/{subtype}/titers.tsv"
            for subtype in config["subtypes"]
        },
    params:
        subtypes=config["subtypes"],
        # include just the circulating strains and recent vaccine strains
        circulating_strain_type=config["circulating_strain_type"],
        recent_vaccine_strains=config["recent_vaccine_strains"],
        # columns in `summarize_titers_csv` with fraction below cutoff 
        frac_below_cols=[
            f"frac_w_titer_below_{config['human_sera_plots_params']['titer_cutoff']}"
        ],
        # prefixes to add to alignments
        prefix_alignment=config["nextstrain-prot-titers-tree_prefix_alignment"],
    conda:
        "seqneut-pipeline/environment.yml"
    log:
        "results/logs/nextstrain_prot_titers_tree_alignment_and_metadata.txt",
    script:
        "scripts/nextstrain_prot_titers_tree_alignment_and_metadata.py"


# run the nextstrain-prot-titers-tree submodule on each lineage
for subtype in config["subtypes"]:
    module_name = f"nextstrain-prot-titers-tree_{subtype}"
    module:
        name: module_name
        snakefile: "nextstrain-prot-titers-tree/Snakefile"
        config: config["nextstrain-prot-titers-tree_config"][subtype]
    use rule * from module_name as module_name*
