###### Input ##########################################

# Library strains
# strain_prots: data/h3_strains.fasta
strain_prots:
  h1: data/h1_strains.fasta
  h3: data/h3_strains.fasta

# GISAID sequences
# gisaid_prots: data/gisaid_circulating_h3.fasta
gisaid_prots: 
  h1: data/gisaid_circulating_h1.fasta
  h3: data/gisaid_circulating_h3.fasta

# Specify protein sequences to search for matches to `strain_prots` to get the
# counts of each strain (variant) at each time.
#
# The `protset` key specifies the set of proteins to look for matches in.
#
# The `trim` entry below specifies to trim the `strain_prots` to that range, and
# then look for matches that contain that trimmed strain protein in `protset`.
# This can be done to just look at a specific region (eg, ectodomain or HA1).
# Also keep in mind the strains in the libraries are engineered to have a chimeric
# signal peptide and endodomain so you probably do not want to require a match to
# that. The trimming is done to indicated range (1, 2, ... numbering, inclusive).
# 
# The `maxdiff` parameter specifies how many differences a protein in `protset`
# can have from the strain. A protein in a `protset` is a match if it
# has <= this many differences to the strain. We take the best match(es) for
# each protein, and if it matches multiple strains they are each
# assigned a fractional count. A differences is any of a single amino-acid
# substitution, insertion, or deletion.
protsets:

protsets:
  h1-gisaid-ha1-within1:
    protset: data/gisaid_circulating_h1.fasta
    trim: [18, 327]
    maxdiff: 1
    group: h1
  h1-gisaid-ha1-exact:
    protset: data/gisaid_circulating_h1.fasta
    trim: [18, 327]
    maxdiff: 0
    group: h1
  h1-gisaid-ectodomain-within1:
    protset: data/gisaid_circulating_h1.fasta
    trim: [18, 327]
    maxdiff: 1
    group: h1
  h3-gisaid-ha1-within1:
    protset: data/gisaid_circulating_h3.fasta
    trim: [20, 348]
    maxdiff: 1
    group: h3
  h3-gisaid-ha1-exact:
    protset: data/gisaid_circulating_h3.fasta
    trim: [20, 348]
    maxdiff: 0
    group: h3
  h3-gisaid-ectodomain-within1:
    protset: data/gisaid_circulating_h3.fasta
    trim: [20, 533]
    maxdiff: 1
    group: h3
    


