name: circulating_HA_analysis
channels:
  - conda-forge
  - bioconda

dependencies:
  - altair
  - regex
  - biopython
  - jupyterlab
  - pandas
  - seaborn
  - snakemake
  - mafft
  - iqtree
  - ete3
  - emboss
  - cd-hit