name: flu_circulating_frequencies
channels:
  - conda-forge
  - bioconda

dependencies:
  - altair
  - biopython
  - cd-hit
  - jupyterlab
  - mafft
  - pandas
  - papermill
  - regex
  - seaborn
  - snakemake
