"""
``snakemake`` file that runs analysis.
"""

# Identify configuration file
configfile: "config.yml"

# Include rules
include: "rules/count_circulating_strains.smk"
include: "rules/generate_summary_notebook.smk"

# Define h1 and h3 combinations
valid_combos = [(v["group"], k) for k, v in config["protsets"].items()]

# Specify output files
rule all:
    """ 
    Target rule.
    """
    input:
        expand(
            "results/notebooks/strain_counts_{group}_{protset}.ipynb",
            zip,
            group=[g for g, p in valid_combos],
            protset=[p for g, p in valid_combos],
        ),
        expand("/fh/fast/bloom_j/computational_notebooks/ckikawa/2025/flu-seqneut-2025/non-pipeline_analyses/flu_circulating_frequencies/results/notebooks/{notebook}.html", notebook=[f.replace('.ipynb', '') for f in os.listdir('results/notebooks') if f.endswith('.ipynb')])
